{% set name = "myhdl" %}
{% set version = "0.11.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e94b5d6d3b750ee9a11f224e393d8724ef3b8eb683b528207ac90887b6e0ca16

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - myhdl

about:
  home: http://www.myhdl.org
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python as a Hardware Description Language
  doc_url: http://docs.myhdl.org/
  dev_url: https://github.com/myhdl/myhdl

extra:
  recipe-maintainers:
    - davidbrochart
